In [1]:
import pandas, warnings

warnings.filterwarnings('ignore')

airurl = '/content/airline.csv'

In [2]:
airtable = pandas.read_table(airurl, sep=',')

airtable.iloc[:5]

     Month  #Passengers
0  1949-01          112
1  1949-02          118
2  1949-03          132
3  1949-04          129
4  1949-05          121

In [3]:
airtable.tail()

       Month  #Passengers
139  1960-08          606
140  1960-09          508
141  1960-10          461
142  1960-11          390
143  1960-12          432